### ISSUE TITLE
Refactor : 발음교정과 억양교정으로 나누는 것으로 기획 변경에 따른 리팩토링

### ISSUE THREAD

**Issue by OH-GITAEK** [OH-GITAEK/allbareum-backend#18]
## 🚀 Description
기존의 통합 발음 교정에서 발음교정과 억양교정으로 나누는 것으로 기획 변경에 따른 수정

## ✅ TODO
- [x] 발음 교정 테스트 코드 수정
- [x] 발음 교정 기능 구현
- [ ] 억양 교정 테스트 코드 작성
- [ ] 억양 교정 기능 구현
