### ISSUE TITLE
Feature : 프로메테우스와 그라파나를 이용한 모니터링 환경 구축

### ISSUE THREAD

**Issue by OH-GITAEK** [OH-GITAEK/allbareum-backend#21]
## 🚀 Description
프로메테우스와 그라파나를 이용하여 모니터링 환경 구축하기

## ✅ TODO
- [x] 환경설정 하기
- [x] 도커 컴포즈 수정하기
- [x] 배포 및 추가 설정
- [ ] 전체 서버 모니터링 환경 구축하기
